### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by micahlt** [Oren-Lindsey/wasteof-client3#1]
Are there any docs planned for this library?

**Comment by Oren-Lindsey** [comment]
there are docs: https://oren-lindsey.github.io/wasteof-client-docs/

**Comment by AwesomePotatoCodes** [comment]
> there are docs: https://oren-lindsey.github.io/wasteof-client-docs/

there's only one topic?

**Comment by Oren-Lindsey** [comment]
> > there are docs: [oren-lindsey.github.io/wasteof-client-docs](https://oren-lindsey.github.io/wasteof-client-docs/)
> 
> there's only one topic?

its meant to be like a guide, click on "setup" and then click on the class you want to use
