### ISSUE TITLE
Type Safety

### ISSUE THREAD

**Issue by mybearworld** [Oren-Lindsey/wasteof-client3#4]
Two things:
- Typescript
- [zod](https://github.com/colinhacks/zod) for verifying that the API returns the expected response

**Comment by mybearworld** [comment]
(Last commit was last year, but I'm raising the issue nonetheless)

**Comment by Oren-Lindsey** [comment]
I kinda stopped working on this, it's pretty buggy and old. Also, it still has wasteof3 support which is deprecated.

**Comment by Oren-Lindsey** [comment]
I want to remake it at some point but I've not been super motivated for coding recently.
